language: python
python:
 - '3.3'
 - '3.5'
 - '3.6'
# Not actually using Travis Python...

before_install:
 - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - ./miniconda.sh -b
 - export PATH=/home/travis/miniconda3/bin:$PATH
 - conda update --yes conda

install:
 - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy pandas

script:
 - python3 -m unittest test.test_parsers 
