language: python
python:
 - '2.7'
# - '3.3'
 - '3.5'
 - '3.6'
# Not actually using Travis Python...

install:
 - sudo apt-get update
 - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
   else
     wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
   fi
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda confg --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a

 - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pandas xlrd
 - source activate test-environment
script:
 - python -m unittest test.test_parsers 
