language: python
python:
 - '3.3'
 - '3.5'
 - '3.6'

install:
 - sudo pip install conda
 - sudo conda init
 - sudo conda update conda --yes
 - deps='pip numpy pandas'
 - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
 - export PATH=$HOME/py/bin:$PATH

script:
 - python3 -m unittest test.test_parsers 
